- hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import VPC Variable
      include_vars: vars/vpc_setup
  
    - name: Create vprofile-vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes 
        dns_hostnames: yes 
        tenancy: default 
        state: "{{state}}"
      register: vpcoutput

    - debug: 
        var: vpcoutput

    - name: Create public subnet 1 in ZONE1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE1}}"
        state: "{{state}}"
        cidr: "{{PubSub1cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-pubsub1
      register: pubsub1_output

    - name: Create public subnet 2 in ZONE2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE2}}"
        state: "{{state}}"
        cidr: "{{PubSub2cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-pubsub2
      register: pubsub2_output

    - name: Create public subnet 3 in ZONE3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE3}}"
        state: "{{state}}"
        cidr: "{{PubSub3cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-pubsub3
      register: pubsub3_output

    - name: Create private subnet 1 in ZONE1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE1}}"
        state: "{{state}}"
        cidr: "{{PrivSub1cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub1
      register: Privsub1_output


    - name: Create private subnet 2 in ZONE2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE2}}"
        state: "{{state}}"
        cidr: "{{PrivSub2cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub2
      register: Privsub2_output
    

    - name: Create private subnet 3 in ZONE3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE3}}"
        state: "{{state}}"
        cidr: "{{PrivSub3cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub3
      register: Privsub3_output
 
    - name: Internet Gateway setup 
      ec2_vpc_igw: 
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags: 
          name: vprofile_IGW
      register: IGW_output


    - name: Setup public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        tags: 
          name: Vprofile_RT
        subnets:
          - "{{pubsub1_output.subnet.id}}"
          - "{{pubsub2_output.subnet.id}}"
          - "{{pubsub3_output.subnet.id}}"
        routes: 
          - dest: 0.0.0.0/0
            gateway_id: "{{IGW_output.gateway_id}}"
      register: pubroute_output

    - name: Setup NAT Gateway
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        subnet_id: "{{pubsub1_output.subnet.id}}"
        wait: yes
        region: "{{region}}"
        if_exist_do_not_create: true
      register: NATGW_output

    - name: Setup private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        tags: 
          name: Vprofile_PrivRT
        subnets:
          - "{{pubsub1_output.subnet.id}}"
          - "{{pubsub2_output.subnet.id}}"
          - "{{pubsub3_output.subnet.id}}"
        routes: 
          - dest: 0.0.0.0/0
            gateway_id: "{{NATGW_output.nat_gateway_id}}"
      register: NATGW_PRIV_output

    - debug: 
        var: "{{item}}"
      loop:
        - vpcoutput.vpc.id
        - pubsub1_output.subnet.id
        - pubsub2_output.subnet.id
        - pubsub3_output.subnet.id
        - Privsub1_output.subnet.id
        - Privsub2_output.subnet.id
        - Privsub2_output.subnet.id
        - IGW_output.gateway_id
        - pubroute_output.route_table.id
        - NATGW_output.nat_gateway_id
        - ATGW_PRIV_output.route_table.id
      

      