- hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import VPC Variable
      include_vars: vars/vpc_setup
  
    - name: Create vprofile-vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes 
        dns_hostnames: yes 
        tenancy: default 
        state: "{{state}}"
      register: vpcoutput

    - debug: 
        var: vpcoutput

    - name: Create public subnet 1 in ZONE1
        ec2_vpc_subnet:
          vpc_id: "{{vpcoutput.vpc.id}}"
          region: "{{region}}"
          az: "{{ZONE1}}"
          state: "{{state}}"
          cidr: "{{PubSub1cidr}}"
          map_public: yes
          resource_tags: 
            name: vprofile-pubsub1
        register: pubsub1_output



      