- hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import VPC Variable
      include_vars: vars/vpc_setup
  
    - name: Create vprofile-vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        dns_support: yes 
        dns_hostnames: yes 
        tenancy: default 
        state: "{{state}}"
      register: vpcoutput

    - debug: 
        var: vpcoutput

    - name: Create public subnet 1 in ZONE1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE1}}"
        state: "{{state}}"
        cidr: "{{PubSub1cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-pubsub1
      register: pubsub1_output

    - name: Create public subnet 2 in ZONE2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE2}}"
        state: "{{state}}"
        cidr: "{{PubSub2cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-pubsub2
      register: pubsub2_output

    - name: Create public subnet 3 in ZONE3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE3}}"
        state: "{{state}}"
        cidr: "{{PubSub3cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-pubsub3
      register: pubsub3_output

    - name: Create private subnet 1 in ZONE1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE1}}"
        state: "{{state}}"
        cidr: "{{PrivSub1cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub1
      register: Privsub1_output


    - name: Create private subnet 2 in ZONE2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE2}}"
        state: "{{state}}"
        cidr: "{{PrivSub2cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub2
      register: Privsub2_output
    

    - name: Create private subnet 3 in ZONE3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        az: "{{ZONE3}}"
        state: "{{state}}"
        cidr: "{{PrivSub3cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub3
      register: Privsub3_output
 


      