- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: VPC setup Variable
      include_vars: vars/vpc-output-vars

    - name: Import vprofile setup 